### ISSUE TITLE
Cannot register new accounts in test

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#42]
At https://sso.test.up2university.eu/simplesaml/module.php/selfregister/newUser.php
I get "Unhandled exception" for any new email address.

Last error code: 5dec80f566

**Comment by michzimny** [comment]
The same when I log in via EduGAIN, possibly as a new account in test (I'm not sure).

**Comment by michzimny** [comment]
Currently, I tried to log in via Google to the test SSO and I see "Preparing your account. This step can take up to a minute." for about 30 minutes. After closing the browser tab and logging in again, the result is the same, the same message.

**Comment by m0ark** [comment]
@michzimny this is resolved by now. A new release of the according module has been rolled out.

**Comment by michzimny** [comment]
@m0ark, is it rolled out to the test instance? 

I'm still experiencing the issue from my first comment here. My error code just obtained is 0a8d29fd3b.

**Comment by m0ark** [comment]
Actually there are 2 different issues here.
I fixed account creation for every onboarding method (except selfregistration).

The other issue is about selfregistering, I didn't have a look at it yet but will have soon.

**Comment by michzimny** [comment]
When could you bring a solution for the self-registration issue?

**Comment by m0ark** [comment]
@michzimny Self-registration is up and running again.
